// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReadEventClient is the client API for ReadEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadEventClient interface {
	// Registering BookEvent with bookmark ID
	Register(ctx context.Context, in *ReadEventRegisterRequest, opts ...grpc.CallOption) (*ReadEventRegisterResponse, error)
	GetByBookID(ctx context.Context, in *GetByBookIDRequest, opts ...grpc.CallOption) (*GetReadEventResponse, error)
}

type readEventClient struct {
	cc grpc.ClientConnInterface
}

func NewReadEventClient(cc grpc.ClientConnInterface) ReadEventClient {
	return &readEventClient{cc}
}

func (c *readEventClient) Register(ctx context.Context, in *ReadEventRegisterRequest, opts ...grpc.CallOption) (*ReadEventRegisterResponse, error) {
	out := new(ReadEventRegisterResponse)
	err := c.cc.Invoke(ctx, "/bookowl.ReadEvent/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readEventClient) GetByBookID(ctx context.Context, in *GetByBookIDRequest, opts ...grpc.CallOption) (*GetReadEventResponse, error) {
	out := new(GetReadEventResponse)
	err := c.cc.Invoke(ctx, "/bookowl.ReadEvent/GetByBookID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadEventServer is the server API for ReadEvent service.
// All implementations must embed UnimplementedReadEventServer
// for forward compatibility
type ReadEventServer interface {
	// Registering BookEvent with bookmark ID
	Register(context.Context, *ReadEventRegisterRequest) (*ReadEventRegisterResponse, error)
	GetByBookID(context.Context, *GetByBookIDRequest) (*GetReadEventResponse, error)
	mustEmbedUnimplementedReadEventServer()
}

// UnimplementedReadEventServer must be embedded to have forward compatible implementations.
type UnimplementedReadEventServer struct {
}

func (UnimplementedReadEventServer) Register(context.Context, *ReadEventRegisterRequest) (*ReadEventRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedReadEventServer) GetByBookID(context.Context, *GetByBookIDRequest) (*GetReadEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByBookID not implemented")
}
func (UnimplementedReadEventServer) mustEmbedUnimplementedReadEventServer() {}

// UnsafeReadEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadEventServer will
// result in compilation errors.
type UnsafeReadEventServer interface {
	mustEmbedUnimplementedReadEventServer()
}

func RegisterReadEventServer(s grpc.ServiceRegistrar, srv ReadEventServer) {
	s.RegisterService(&ReadEvent_ServiceDesc, srv)
}

func _ReadEvent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEventRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadEventServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookowl.ReadEvent/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadEventServer).Register(ctx, req.(*ReadEventRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadEvent_GetByBookID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBookIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadEventServer).GetByBookID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookowl.ReadEvent/GetByBookID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadEventServer).GetByBookID(ctx, req.(*GetByBookIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadEvent_ServiceDesc is the grpc.ServiceDesc for ReadEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookowl.ReadEvent",
	HandlerType: (*ReadEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ReadEvent_Register_Handler,
		},
		{
			MethodName: "GetByBookID",
			Handler:    _ReadEvent_GetByBookID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "read_event.proto",
}
