# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bookowl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bookowl
  pod 'HMSegmentedControl'
 
  target 'BookowlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookowlUITests' do
    # Pods for testing
  end

end
