version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./db/:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost -ppassword"
      timeout: 20s
      retries: 10
