# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='book.proto',
  package='bookowl',
  syntax='proto3',
  serialized_options=b'Z$github.com/jphacks/B_2109/server/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbook.proto\x12\x07\x62ookowl\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n\x13\x42ookRegisterRequest\x12$\n\tbook_info\x18\x01 \x01(\x0b\x32\x11.bookowl.BookInfo\x12\x13\n\x0b\x62ookmark_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"Q\n\x14\x42ookRegisterResponse\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\x08\x42ookInfo\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x17\n\x0f\x62ook_mili_width\x18\x02 \x01(\x03\x32O\n\x04\x42ook\x12G\n\x08Register\x12\x1c.bookowl.BookRegisterRequest\x1a\x1d.bookowl.BookRegisterResponseB&Z$github.com/jphacks/B_2109/server/apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_BOOKREGISTERREQUEST = _descriptor.Descriptor(
  name='BookRegisterRequest',
  full_name='bookowl.BookRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_info', full_name='bookowl.BookRegisterRequest.book_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bookmark_id', full_name='bookowl.BookRegisterRequest.bookmark_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.BookRegisterRequest.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=153,
)


_BOOKREGISTERRESPONSE = _descriptor.Descriptor(
  name='BookRegisterResponse',
  full_name='bookowl.BookRegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book_id', full_name='bookowl.BookRegisterResponse.book_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.BookRegisterResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=236,
)


_BOOKINFO = _descriptor.Descriptor(
  name='BookInfo',
  full_name='bookowl.BookInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='bookowl.BookInfo.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='book_mili_width', full_name='bookowl.BookInfo.book_mili_width', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=287,
)

_BOOKREGISTERREQUEST.fields_by_name['book_info'].message_type = _BOOKINFO
_BOOKREGISTERRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['BookRegisterRequest'] = _BOOKREGISTERREQUEST
DESCRIPTOR.message_types_by_name['BookRegisterResponse'] = _BOOKREGISTERRESPONSE
DESCRIPTOR.message_types_by_name['BookInfo'] = _BOOKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookRegisterRequest = _reflection.GeneratedProtocolMessageType('BookRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKREGISTERREQUEST,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.BookRegisterRequest)
  })
_sym_db.RegisterMessage(BookRegisterRequest)

BookRegisterResponse = _reflection.GeneratedProtocolMessageType('BookRegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOKREGISTERRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.BookRegisterResponse)
  })
_sym_db.RegisterMessage(BookRegisterResponse)

BookInfo = _reflection.GeneratedProtocolMessageType('BookInfo', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINFO,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.BookInfo)
  })
_sym_db.RegisterMessage(BookInfo)


DESCRIPTOR._options = None

_BOOK = _descriptor.ServiceDescriptor(
  name='Book',
  full_name='bookowl.Book',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=368,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='bookowl.Book.Register',
    index=0,
    containing_service=None,
    input_type=_BOOKREGISTERREQUEST,
    output_type=_BOOKREGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOK)

DESCRIPTOR.services_by_name['Book'] = _BOOK

# @@protoc_insertion_point(module_scope)
