# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import book_pb2 as book__pb2


class BookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterBook = channel.unary_unary(
                '/bookowl.Book/RegisterBook',
                request_serializer=book__pb2.RegisterBookRequest.SerializeToString,
                response_deserializer=book__pb2.RegisterBookResponse.FromString,
                )
        self.GetBooksByUserID = channel.unary_unary(
                '/bookowl.Book/GetBooksByUserID',
                request_serializer=book__pb2.GetBooksByUserIDRequest.SerializeToString,
                response_deserializer=book__pb2.GetBooksResponse.FromString,
                )
        self.GetBooksByBookmarkID = channel.unary_unary(
                '/bookowl.Book/GetBooksByBookmarkID',
                request_serializer=book__pb2.GetBooksByBookmarkIDRequest.SerializeToString,
                response_deserializer=book__pb2.GetBooksResponse.FromString,
                )
        self.UpdateBookmarkID = channel.unary_unary(
                '/bookowl.Book/UpdateBookmarkID',
                request_serializer=book__pb2.UpdateBookmarkIDRequest.SerializeToString,
                response_deserializer=book__pb2.UpdateBookResponse.FromString,
                )
        self.UpdateReadStatus = channel.unary_unary(
                '/bookowl.Book/UpdateReadStatus',
                request_serializer=book__pb2.UpdateReadStatusRequest.SerializeToString,
                response_deserializer=book__pb2.UpdateBookResponse.FromString,
                )
        self.GetProgressByUserID = channel.unary_unary(
                '/bookowl.Book/GetProgressByUserID',
                request_serializer=book__pb2.GetProgressByUserIDRequest.SerializeToString,
                response_deserializer=book__pb2.GetProgressByUserIDResponse.FromString,
                )
        self.GetReadAmountPagesByUserIDWithDuration = channel.unary_unary(
                '/bookowl.Book/GetReadAmountPagesByUserIDWithDuration',
                request_serializer=book__pb2.GetReadAmountPagesByUserIDWithDurationRequest.SerializeToString,
                response_deserializer=book__pb2.GetReadAmountPagesByUserIDWithDurationResponse.FromString,
                )


class BookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterBook(self, request, context):
        """Registering Book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByBookmarkID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBookmarkID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgressByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadAmountPagesByUserIDWithDuration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBook,
                    request_deserializer=book__pb2.RegisterBookRequest.FromString,
                    response_serializer=book__pb2.RegisterBookResponse.SerializeToString,
            ),
            'GetBooksByUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksByUserID,
                    request_deserializer=book__pb2.GetBooksByUserIDRequest.FromString,
                    response_serializer=book__pb2.GetBooksResponse.SerializeToString,
            ),
            'GetBooksByBookmarkID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksByBookmarkID,
                    request_deserializer=book__pb2.GetBooksByBookmarkIDRequest.FromString,
                    response_serializer=book__pb2.GetBooksResponse.SerializeToString,
            ),
            'UpdateBookmarkID': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBookmarkID,
                    request_deserializer=book__pb2.UpdateBookmarkIDRequest.FromString,
                    response_serializer=book__pb2.UpdateBookResponse.SerializeToString,
            ),
            'UpdateReadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReadStatus,
                    request_deserializer=book__pb2.UpdateReadStatusRequest.FromString,
                    response_serializer=book__pb2.UpdateBookResponse.SerializeToString,
            ),
            'GetProgressByUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgressByUserID,
                    request_deserializer=book__pb2.GetProgressByUserIDRequest.FromString,
                    response_serializer=book__pb2.GetProgressByUserIDResponse.SerializeToString,
            ),
            'GetReadAmountPagesByUserIDWithDuration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadAmountPagesByUserIDWithDuration,
                    request_deserializer=book__pb2.GetReadAmountPagesByUserIDWithDurationRequest.FromString,
                    response_serializer=book__pb2.GetReadAmountPagesByUserIDWithDurationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookowl.Book', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Book(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/RegisterBook',
            book__pb2.RegisterBookRequest.SerializeToString,
            book__pb2.RegisterBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksByUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/GetBooksByUserID',
            book__pb2.GetBooksByUserIDRequest.SerializeToString,
            book__pb2.GetBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksByBookmarkID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/GetBooksByBookmarkID',
            book__pb2.GetBooksByBookmarkIDRequest.SerializeToString,
            book__pb2.GetBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBookmarkID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/UpdateBookmarkID',
            book__pb2.UpdateBookmarkIDRequest.SerializeToString,
            book__pb2.UpdateBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateReadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/UpdateReadStatus',
            book__pb2.UpdateReadStatusRequest.SerializeToString,
            book__pb2.UpdateBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProgressByUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/GetProgressByUserID',
            book__pb2.GetProgressByUserIDRequest.SerializeToString,
            book__pb2.GetProgressByUserIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReadAmountPagesByUserIDWithDuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Book/GetReadAmountPagesByUserIDWithDuration',
            book__pb2.GetReadAmountPagesByUserIDWithDurationRequest.SerializeToString,
            book__pb2.GetReadAmountPagesByUserIDWithDurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
