# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goal.proto',
  package='bookowl',
  syntax='proto3',
  serialized_options=b'Z$github.com/jphacks/B_2109/server/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngoal.proto\x12\x07\x62ookowl\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\x13RegisterGoalRequest\x12$\n\tgoal_info\x18\x01 \x01(\x0b\x32\x11.bookowl.GoalInfo\"Q\n\x14RegisterGoalResponse\x12\x0f\n\x07goal_id\x18\x01 \x01(\x04\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\")\n\x16GetGoalByUserIDRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"a\n\x0fGetGoalResponse\x12$\n\tgoal_info\x18\x01 \x03(\x0b\x32\x11.bookowl.GoalInfo\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"T\n\x17UpdateGoalStatusRequest\x12\x0f\n\x07goal_id\x18\x01 \x01(\x04\x12(\n\x0bgoal_status\x18\x02 \x01(\x0e\x32\x13.bookowl.GoalStatus\"d\n\x12UpdateGoalResponse\x12$\n\tgoal_info\x18\x01 \x01(\x0b\x32\x11.bookowl.GoalInfo\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xe4\x01\n\x08GoalInfo\x12\x0f\n\x07goal_id\x18\x01 \x01(\x04\x12.\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13time_amount_minutes\x18\x04 \x01(\x03\x12\x11\n\tnum_pages\x18\x05 \x01(\x03\x12(\n\x0bgoal_status\x18\x06 \x01(\x0e\x32\x13.bookowl.GoalStatus\x12\x0f\n\x07user_id\x18\x07 \x01(\x04*R\n\nGoalStatus\x12\x10\n\x0cGOAL_PENDING\x10\x00\x12\x0e\n\nGOAL_DOING\x10\x01\x12\x11\n\rGOAL_COMPLETE\x10\x02\x12\x0f\n\x0bGOAL_FAILED\x10\x03\x32\xec\x01\n\x04Goal\x12G\n\x08Register\x12\x1c.bookowl.RegisterGoalRequest\x1a\x1d.bookowl.RegisterGoalResponse\x12H\n\x0bGetByUserID\x12\x1f.bookowl.GetGoalByUserIDRequest\x1a\x18.bookowl.GetGoalResponse\x12Q\n\x10UpdateGoalStatus\x12 .bookowl.UpdateGoalStatusRequest\x1a\x1b.bookowl.UpdateGoalResponseB&Z$github.com/jphacks/B_2109/server/apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_GOALSTATUS = _descriptor.EnumDescriptor(
  name='GoalStatus',
  full_name='bookowl.GoalStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOAL_PENDING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_DOING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_COMPLETE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_FAILED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=761,
  serialized_end=843,
)
_sym_db.RegisterEnumDescriptor(_GOALSTATUS)

GoalStatus = enum_type_wrapper.EnumTypeWrapper(_GOALSTATUS)
GOAL_PENDING = 0
GOAL_DOING = 1
GOAL_COMPLETE = 2
GOAL_FAILED = 3



_REGISTERGOALREQUEST = _descriptor.Descriptor(
  name='RegisterGoalRequest',
  full_name='bookowl.RegisterGoalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_info', full_name='bookowl.RegisterGoalRequest.goal_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=115,
)


_REGISTERGOALRESPONSE = _descriptor.Descriptor(
  name='RegisterGoalResponse',
  full_name='bookowl.RegisterGoalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_id', full_name='bookowl.RegisterGoalResponse.goal_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.RegisterGoalResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=198,
)


_GETGOALBYUSERIDREQUEST = _descriptor.Descriptor(
  name='GetGoalByUserIDRequest',
  full_name='bookowl.GetGoalByUserIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.GetGoalByUserIDRequest.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=241,
)


_GETGOALRESPONSE = _descriptor.Descriptor(
  name='GetGoalResponse',
  full_name='bookowl.GetGoalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_info', full_name='bookowl.GetGoalResponse.goal_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.GetGoalResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=340,
)


_UPDATEGOALSTATUSREQUEST = _descriptor.Descriptor(
  name='UpdateGoalStatusRequest',
  full_name='bookowl.UpdateGoalStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_id', full_name='bookowl.UpdateGoalStatusRequest.goal_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_status', full_name='bookowl.UpdateGoalStatusRequest.goal_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=426,
)


_UPDATEGOALRESPONSE = _descriptor.Descriptor(
  name='UpdateGoalResponse',
  full_name='bookowl.UpdateGoalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_info', full_name='bookowl.UpdateGoalResponse.goal_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.UpdateGoalResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=528,
)


_GOALINFO = _descriptor.Descriptor(
  name='GoalInfo',
  full_name='bookowl.GoalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_id', full_name='bookowl.GoalInfo.goal_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='bookowl.GoalInfo.start_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='bookowl.GoalInfo.end_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_amount_minutes', full_name='bookowl.GoalInfo.time_amount_minutes', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='bookowl.GoalInfo.num_pages', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_status', full_name='bookowl.GoalInfo.goal_status', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.GoalInfo.user_id', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=759,
)

_REGISTERGOALREQUEST.fields_by_name['goal_info'].message_type = _GOALINFO
_REGISTERGOALRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETGOALRESPONSE.fields_by_name['goal_info'].message_type = _GOALINFO
_GETGOALRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_UPDATEGOALSTATUSREQUEST.fields_by_name['goal_status'].enum_type = _GOALSTATUS
_UPDATEGOALRESPONSE.fields_by_name['goal_info'].message_type = _GOALINFO
_UPDATEGOALRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['start_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['goal_status'].enum_type = _GOALSTATUS
DESCRIPTOR.message_types_by_name['RegisterGoalRequest'] = _REGISTERGOALREQUEST
DESCRIPTOR.message_types_by_name['RegisterGoalResponse'] = _REGISTERGOALRESPONSE
DESCRIPTOR.message_types_by_name['GetGoalByUserIDRequest'] = _GETGOALBYUSERIDREQUEST
DESCRIPTOR.message_types_by_name['GetGoalResponse'] = _GETGOALRESPONSE
DESCRIPTOR.message_types_by_name['UpdateGoalStatusRequest'] = _UPDATEGOALSTATUSREQUEST
DESCRIPTOR.message_types_by_name['UpdateGoalResponse'] = _UPDATEGOALRESPONSE
DESCRIPTOR.message_types_by_name['GoalInfo'] = _GOALINFO
DESCRIPTOR.enum_types_by_name['GoalStatus'] = _GOALSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterGoalRequest = _reflection.GeneratedProtocolMessageType('RegisterGoalRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERGOALREQUEST,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.RegisterGoalRequest)
  })
_sym_db.RegisterMessage(RegisterGoalRequest)

RegisterGoalResponse = _reflection.GeneratedProtocolMessageType('RegisterGoalResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERGOALRESPONSE,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.RegisterGoalResponse)
  })
_sym_db.RegisterMessage(RegisterGoalResponse)

GetGoalByUserIDRequest = _reflection.GeneratedProtocolMessageType('GetGoalByUserIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGOALBYUSERIDREQUEST,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GetGoalByUserIDRequest)
  })
_sym_db.RegisterMessage(GetGoalByUserIDRequest)

GetGoalResponse = _reflection.GeneratedProtocolMessageType('GetGoalResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETGOALRESPONSE,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GetGoalResponse)
  })
_sym_db.RegisterMessage(GetGoalResponse)

UpdateGoalStatusRequest = _reflection.GeneratedProtocolMessageType('UpdateGoalStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEGOALSTATUSREQUEST,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.UpdateGoalStatusRequest)
  })
_sym_db.RegisterMessage(UpdateGoalStatusRequest)

UpdateGoalResponse = _reflection.GeneratedProtocolMessageType('UpdateGoalResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEGOALRESPONSE,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.UpdateGoalResponse)
  })
_sym_db.RegisterMessage(UpdateGoalResponse)

GoalInfo = _reflection.GeneratedProtocolMessageType('GoalInfo', (_message.Message,), {
  'DESCRIPTOR' : _GOALINFO,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GoalInfo)
  })
_sym_db.RegisterMessage(GoalInfo)


DESCRIPTOR._options = None

_GOAL = _descriptor.ServiceDescriptor(
  name='Goal',
  full_name='bookowl.Goal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=846,
  serialized_end=1082,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='bookowl.Goal.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTERGOALREQUEST,
    output_type=_REGISTERGOALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetByUserID',
    full_name='bookowl.Goal.GetByUserID',
    index=1,
    containing_service=None,
    input_type=_GETGOALBYUSERIDREQUEST,
    output_type=_GETGOALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateGoalStatus',
    full_name='bookowl.Goal.UpdateGoalStatus',
    index=2,
    containing_service=None,
    input_type=_UPDATEGOALSTATUSREQUEST,
    output_type=_UPDATEGOALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOAL)

DESCRIPTOR.services_by_name['Goal'] = _GOAL

# @@protoc_insertion_point(module_scope)
