# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goal.proto',
  package='bookowl',
  syntax='proto3',
  serialized_options=b'Z$github.com/jphacks/B_2109/server/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngoal.proto\x12\x07\x62ookowl\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n\x11\x43reateGoalRequest\x12\x11\n\tnum_pages\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"d\n\x12\x43reateGoalResponse\x12$\n\tgoal_info\x18\x01 \x01(\x0b\x32\x11.bookowl.GoalInfo\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x0fGetGoalsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"c\n\x10GetGoalsResponse\x12%\n\ngoals_info\x18\x01 \x03(\x0b\x32\x11.bookowl.GoalInfo\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xcd\x01\n\x08GoalInfo\x12\x0f\n\x07goal_id\x18\x01 \x01(\x04\x12.\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tnum_pages\x18\x05 \x01(\x03\x12(\n\x0bgoal_status\x18\x06 \x01(\x0e\x32\x13.bookowl.GoalStatus\x12\x0f\n\x07user_id\x18\x07 \x01(\x04J\x04\x08\x04\x10\x05*d\n\nGoalStatus\x12\x10\n\x0cGOAL_UNKNOWN\x10\x00\x12\x10\n\x0cGOAL_PENDING\x10\x01\x12\x0e\n\nGOAL_DOING\x10\x02\x12\x11\n\rGOAL_COMPLETE\x10\x03\x12\x0f\n\x0bGOAL_FAILED\x10\x04\x32\x8e\x01\n\x04Goal\x12\x45\n\nCreateGoal\x12\x1a.bookowl.CreateGoalRequest\x1a\x1b.bookowl.CreateGoalResponse\x12?\n\x08GetGoals\x12\x18.bookowl.GetGoalsRequest\x1a\x19.bookowl.GetGoalsResponseB&Z$github.com/jphacks/B_2109/server/apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_GOALSTATUS = _descriptor.EnumDescriptor(
  name='GoalStatus',
  full_name='bookowl.GoalStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOAL_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_PENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_DOING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_COMPLETE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GOAL_FAILED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=602,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_GOALSTATUS)

GoalStatus = enum_type_wrapper.EnumTypeWrapper(_GOALSTATUS)
GOAL_UNKNOWN = 0
GOAL_PENDING = 1
GOAL_DOING = 2
GOAL_COMPLETE = 3
GOAL_FAILED = 4



_CREATEGOALREQUEST = _descriptor.Descriptor(
  name='CreateGoalRequest',
  full_name='bookowl.CreateGoalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='bookowl.CreateGoalRequest.num_pages', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.CreateGoalRequest.user_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.CreateGoalRequest.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=153,
)


_CREATEGOALRESPONSE = _descriptor.Descriptor(
  name='CreateGoalResponse',
  full_name='bookowl.CreateGoalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_info', full_name='bookowl.CreateGoalResponse.goal_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.CreateGoalResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=255,
)


_GETGOALSREQUEST = _descriptor.Descriptor(
  name='GetGoalsRequest',
  full_name='bookowl.GetGoalsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.GetGoalsRequest.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=291,
)


_GETGOALSRESPONSE = _descriptor.Descriptor(
  name='GetGoalsResponse',
  full_name='bookowl.GetGoalsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goals_info', full_name='bookowl.GetGoalsResponse.goals_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='bookowl.GetGoalsResponse.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=392,
)


_GOALINFO = _descriptor.Descriptor(
  name='GoalInfo',
  full_name='bookowl.GoalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_id', full_name='bookowl.GoalInfo.goal_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='bookowl.GoalInfo.start_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='bookowl.GoalInfo.end_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='bookowl.GoalInfo.num_pages', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_status', full_name='bookowl.GoalInfo.goal_status', index=4,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='bookowl.GoalInfo.user_id', index=5,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=600,
)

_CREATEGOALREQUEST.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CREATEGOALRESPONSE.fields_by_name['goal_info'].message_type = _GOALINFO
_CREATEGOALRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETGOALSRESPONSE.fields_by_name['goals_info'].message_type = _GOALINFO
_GETGOALSRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['start_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GOALINFO.fields_by_name['goal_status'].enum_type = _GOALSTATUS
DESCRIPTOR.message_types_by_name['CreateGoalRequest'] = _CREATEGOALREQUEST
DESCRIPTOR.message_types_by_name['CreateGoalResponse'] = _CREATEGOALRESPONSE
DESCRIPTOR.message_types_by_name['GetGoalsRequest'] = _GETGOALSREQUEST
DESCRIPTOR.message_types_by_name['GetGoalsResponse'] = _GETGOALSRESPONSE
DESCRIPTOR.message_types_by_name['GoalInfo'] = _GOALINFO
DESCRIPTOR.enum_types_by_name['GoalStatus'] = _GOALSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGoalRequest = _reflection.GeneratedProtocolMessageType('CreateGoalRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGOALREQUEST,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.CreateGoalRequest)
  })
_sym_db.RegisterMessage(CreateGoalRequest)

CreateGoalResponse = _reflection.GeneratedProtocolMessageType('CreateGoalResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGOALRESPONSE,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.CreateGoalResponse)
  })
_sym_db.RegisterMessage(CreateGoalResponse)

GetGoalsRequest = _reflection.GeneratedProtocolMessageType('GetGoalsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGOALSREQUEST,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GetGoalsRequest)
  })
_sym_db.RegisterMessage(GetGoalsRequest)

GetGoalsResponse = _reflection.GeneratedProtocolMessageType('GetGoalsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETGOALSRESPONSE,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GetGoalsResponse)
  })
_sym_db.RegisterMessage(GetGoalsResponse)

GoalInfo = _reflection.GeneratedProtocolMessageType('GoalInfo', (_message.Message,), {
  'DESCRIPTOR' : _GOALINFO,
  '__module__' : 'goal_pb2'
  # @@protoc_insertion_point(class_scope:bookowl.GoalInfo)
  })
_sym_db.RegisterMessage(GoalInfo)


DESCRIPTOR._options = None

_GOAL = _descriptor.ServiceDescriptor(
  name='Goal',
  full_name='bookowl.Goal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=705,
  serialized_end=847,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGoal',
    full_name='bookowl.Goal.CreateGoal',
    index=0,
    containing_service=None,
    input_type=_CREATEGOALREQUEST,
    output_type=_CREATEGOALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGoals',
    full_name='bookowl.Goal.GetGoals',
    index=1,
    containing_service=None,
    input_type=_GETGOALSREQUEST,
    output_type=_GETGOALSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOAL)

DESCRIPTOR.services_by_name['Goal'] = _GOAL

# @@protoc_insertion_point(module_scope)
