# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import match_pb2 as match__pb2


class MatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterOpponents = channel.unary_unary(
                '/bookowl.Match/RegisterOpponents',
                request_serializer=match__pb2.RegisterOpponentsRequest.SerializeToString,
                response_deserializer=match__pb2.RegisterOpponentsResponse.FromString,
                )
        self.GetOpponents = channel.unary_unary(
                '/bookowl.Match/GetOpponents',
                request_serializer=match__pb2.GetOpponentsRequest.SerializeToString,
                response_deserializer=match__pb2.GetOpponentsResponse.FromString,
                )
        self.GetRanking = channel.unary_unary(
                '/bookowl.Match/GetRanking',
                request_serializer=match__pb2.GetRankingRequest.SerializeToString,
                response_deserializer=match__pb2.GetRankingResponse.FromString,
                )


class MatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterOpponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRanking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterOpponents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterOpponents,
                    request_deserializer=match__pb2.RegisterOpponentsRequest.FromString,
                    response_serializer=match__pb2.RegisterOpponentsResponse.SerializeToString,
            ),
            'GetOpponents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpponents,
                    request_deserializer=match__pb2.GetOpponentsRequest.FromString,
                    response_serializer=match__pb2.GetOpponentsResponse.SerializeToString,
            ),
            'GetRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRanking,
                    request_deserializer=match__pb2.GetRankingRequest.FromString,
                    response_serializer=match__pb2.GetRankingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookowl.Match', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Match(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterOpponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Match/RegisterOpponents',
            match__pb2.RegisterOpponentsRequest.SerializeToString,
            match__pb2.RegisterOpponentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOpponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Match/GetOpponents',
            match__pb2.GetOpponentsRequest.SerializeToString,
            match__pb2.GetOpponentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.Match/GetRanking',
            match__pb2.GetRankingRequest.SerializeToString,
            match__pb2.GetRankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
