# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import read_event_pb2 as read__event__pb2


class ReadEventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/bookowl.ReadEvent/Register',
                request_serializer=read__event__pb2.ReadEventRegisterRequest.SerializeToString,
                response_deserializer=read__event__pb2.ReadEventRegisterResponse.FromString,
                )
        self.GetByBookID = channel.unary_unary(
                '/bookowl.ReadEvent/GetByBookID',
                request_serializer=read__event__pb2.GetByBookIDRequest.SerializeToString,
                response_deserializer=read__event__pb2.GetReadEventResponse.FromString,
                )


class ReadEventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Registering BookEvent with bookmark ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByBookID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReadEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=read__event__pb2.ReadEventRegisterRequest.FromString,
                    response_serializer=read__event__pb2.ReadEventRegisterResponse.SerializeToString,
            ),
            'GetByBookID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByBookID,
                    request_deserializer=read__event__pb2.GetByBookIDRequest.FromString,
                    response_serializer=read__event__pb2.GetReadEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookowl.ReadEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReadEvent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.ReadEvent/Register',
            read__event__pb2.ReadEventRegisterRequest.SerializeToString,
            read__event__pb2.ReadEventRegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetByBookID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookowl.ReadEvent/GetByBookID',
            read__event__pb2.GetByBookIDRequest.SerializeToString,
            read__event__pb2.GetReadEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
