name: docker
on:
  push:
    branches:
    - master
    paths:
    - 'server/**'

jobs:
  docker:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: chez-shanpu
        password: ${{ secrets.SHANPU_GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/docker/bookowl.Dockerfile
        push: true
        tags: |
          ghcr.io/chez-shanpu/bookowl:latest
