name: release
on:
  push:
    tags:
    - '*'
jobs:
  release:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare for image tag
      id: prep
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo ::set-output name=version::${VERSION}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/docker/bookowl.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/b_2109/bookowl-server:stable
          ghcr.io/${{ github.repository_owner }}/b_2109/bookowl-server:${{ steps.prep.outputs.version }}